apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-telus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-telus
  template:
    metadata:
      labels:
        app: hello-telus
    spec:
      containers:
        - name: hello-telus
          image: gcr.io/unogwudan-test/hello-telus:${_SHORT_SHA}
          ports:
            - containerPort: 8080
          resources:
#            requests:
#              cpu: "100m"
#              memory: "128Mi"
#            limits:
#              cpu: "200m"
#              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: GOOGLE_CLOUD_PUBSUB_CREDENTIALS
              value: /var/secrets/google/pubsub-service-account.json
          volumeMounts:
            - name: pubsub-service-account-vol
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: pubsub-service-account-vol
          secret:
            secretName: pubsub-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: hello-telus
spec:
  selector:
    app: hello-telus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-telus-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-telus
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50  # Target 50% CPU utilization
